# Generated by Django 4.2.23 on 2025-08-19 21:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox (Test)'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('public_key', models.CharField(help_text='Clé publique Notchpay', max_length=200)),
                ('private_key', models.CharField(help_text='Clé privée Notchpay', max_length=200)),
                ('webhook_url', models.URLField(blank=True, help_text='URL de réception des webhooks', null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret pour vérifier les signatures webhook', max_length=200, null=True)),
                ('default_currency', models.CharField(choices=[('XAF', 'Franc CFA (CEMAC)'), ('XOF', 'Franc CFA (UEMOA)'), ('USD', 'Dollar américain'), ('EUR', 'Euro')], default='XAF', max_length=3)),
                ('default_return_url', models.URLField(blank=True, help_text='URL de retour par défaut après paiement', null=True)),
                ('default_cancel_url', models.URLField(blank=True, help_text="URL de retour par défaut en cas d'annulation", null=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=30, help_text='Timeout pour les requêtes API (secondes)')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Nombre maximum de tentatives')),
                ('is_active', models.BooleanField(default=True, help_text='Active/désactive le système de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration de paiement',
                'verbose_name_plural': 'Configurations de paiement',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notchpay_transaction_id', models.CharField(blank=True, help_text='ID de transaction fourni par Notchpay', max_length=100, null=True, unique=True)),
                ('reference', models.CharField(help_text='Référence unique interne', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant en unité principale de la devise', max_digits=10)),
                ('currency', models.CharField(choices=[('XAF', 'Franc CFA (CEMAC)'), ('XOF', 'Franc CFA (UEMOA)'), ('USD', 'Dollar américain'), ('EUR', 'Euro')], default='XAF', max_length=3)),
                ('description', models.TextField(help_text='Description du paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('expired', 'Expiré'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('mtn_momo', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('express_union', 'Express Union'), ('card', 'Carte bancaire'), ('bank_transfer', 'Virement bancaire')], max_length=20, null=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('authorization_url', models.URLField(blank=True, help_text='URL de redirection fournie par Notchpay', null=True)),
                ('return_url', models.URLField(blank=True, help_text='URL de retour après paiement', null=True)),
                ('cancel_url', models.URLField(blank=True, help_text="URL de retour en cas d'annulation", null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Métadonnées additionnelles')),
                ('notchpay_response', models.JSONField(default=dict, help_text="Réponse complète de l'API Notchpay")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Date et heure du paiement réussi', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Date d'expiration de la transaction", null=True)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Frais de traitement', max_digits=10)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montant net après déduction des frais', max_digits=10, null=True)),
                ('error_code', models.CharField(blank=True, help_text="Code d'erreur en cas d'échec", max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur détaillé", null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type de contenu payé (cours, quiz, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(help_text="ID unique de l'événement Notchpay", max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('payment.completed', 'Paiement terminé'), ('payment.failed', 'Paiement échoué'), ('payment.pending', 'Paiement en attente'), ('payment.cancelled', 'Paiement annulé'), ('refund.created', 'Remboursement créé'), ('refund.completed', 'Remboursement terminé')], max_length=50)),
                ('data', models.JSONField(help_text="Données complètes de l'événement webhook")),
                ('signature', models.CharField(help_text='Signature de vérification du webhook', max_length=500)),
                ('processed', models.BooleanField(default=False, help_text="Indique si l'événement a été traité")),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur si le traitement a échoué", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Événement Webhook',
                'verbose_name_plural': 'Événements Webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notchpay_refund_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant du remboursement', max_digits=10)),
                ('reason', models.TextField(help_text='Raison du remboursement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('notchpay_response', models.JSONField(default=dict, help_text="Réponse de l'API Notchpay pour le remboursement")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.paymenttransaction')),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_92d873_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['notchpay_transaction_id'], name='payments_pa_notchpa_0d8fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference'], name='payments_pa_referen_72073c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_c4e513_idx'),
        ),
    ]
