# Generated by Django 5.0.6 on 2025-08-20 23:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Numéro de facture généré automatiquement",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("billing_name", models.CharField(max_length=200)),
                ("billing_email", models.EmailField(max_length=254)),
                ("billing_phone", models.CharField(blank=True, max_length=20)),
                ("billing_address", models.TextField(blank=True)),
                ("billing_city", models.CharField(blank=True, max_length=100)),
                (
                    "billing_country",
                    models.CharField(default="Cameroun", max_length=100),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="XAF", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyée"),
                            ("paid", "Payée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Fichier PDF de la facture",
                        null=True,
                        upload_to="invoices/pdf/",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_opened", models.BooleanField(default=False)),
                ("email_opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        help_text="Transaction associée à cette facture",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="payments.paymenttransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invoice_number"], name="payments_in_invoice_3fa711_idx"
                    ),
                    models.Index(
                        fields=["user", "status"], name="payments_in_user_id_a545de_idx"
                    ),
                    models.Index(
                        fields=["issue_date", "status"],
                        name="payments_in_issue_d_9006eb_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="payments_in_status_a745e9_idx",
                    ),
                ],
            },
        ),
    ]
