# Generated by Django 4.2.23 on 2025-08-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0003_alter_user_phone_number_studentprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='courses.course'),
        ),
    ]
