# Generated by Django 4.2.23 on 2025-08-19 12:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_enrollment_coursereview_coursefavorite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quiz_type', models.CharField(choices=[('lesson', 'Quiz de leçon'), ('module', 'Quiz de module'), ('final', 'Examen final'), ('practice', "Quiz d'entraînement")], default='lesson', max_length=20, verbose_name='Type de quiz')),
                ('difficulty', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('expert', 'Expert')], default='beginner', max_length=20, verbose_name='Niveau de difficulté')),
                ('time_limit', models.PositiveIntegerField(blank=True, help_text='Durée en minutes (laisser vide pour illimité)', null=True, verbose_name='Limite de temps')),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='Nombre maximum de tentatives autorisées', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Tentatives maximum')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Score minimum pour réussir (en pourcentage)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de passage')),
                ('randomize_questions', models.BooleanField(default=False, help_text="Mélanger l'ordre des questions", verbose_name='Questions aléatoires')),
                ('randomize_answers', models.BooleanField(default=False, help_text="Mélanger l'ordre des réponses", verbose_name='Réponses aléatoires')),
                ('show_correct_answers', models.BooleanField(default=True, help_text='Afficher les bonnes réponses après la tentative', verbose_name='Afficher les corrections')),
                ('show_score_immediately', models.BooleanField(default=True, help_text='Afficher le score immédiatement après soumission', verbose_name='Score immédiat')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('is_required', models.BooleanField(default=False, help_text='Quiz obligatoire pour la progression', verbose_name='Obligatoire')),
                ('available_from', models.DateTimeField(blank=True, help_text="Date/heure d'ouverture du quiz", null=True, verbose_name='Disponible à partir de')),
                ('available_until', models.DateTimeField(blank=True, help_text='Date/heure de fermeture du quiz', null=True, verbose_name="Disponible jusqu'à")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course', verbose_name='Cours')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.lesson', verbose_name='Leçon')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('submitted', 'Soumise'), ('graded', 'Notée'), ('expired', 'Expirée')], default='in_progress', max_length=20, verbose_name='Statut')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='Numéro de tentative')),
                ('score', models.FloatField(blank=True, help_text='Score obtenu (en pourcentage)', null=True, verbose_name='Score')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Points obtenus')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Total des points')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Commencée à')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Soumise à')),
                ('time_taken', models.DurationField(blank=True, help_text='Temps pris pour compléter le quiz', null=True, verbose_name='Temps pris')),
                ('expires_at', models.DateTimeField(blank=True, help_text="Date d'expiration si limite de temps", null=True, verbose_name='Expire à')),
                ('questions_order', models.TextField(help_text='Ordre des questions pour cette tentative (JSON)', verbose_name='Ordre des questions')),
                ('answers_data', models.TextField(default='{}', help_text='Données des réponses (JSON)', verbose_name='Données des réponses')),
                ('passed', models.BooleanField(default=False, verbose_name='Réussi')),
                ('feedback', models.TextField(blank=True, help_text="Feedback personnalisé de l'instructeur", verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz', verbose_name='Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Tentative de quiz',
                'verbose_name_plural': 'Tentatives de quiz',
                'ordering': ['-started_at'],
                'unique_together': {('quiz', 'user', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Texte de la question')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'QCM (choix multiple)'), ('single_choice', 'QCU (choix unique)'), ('true_false', 'Vrai/Faux'), ('short_answer', 'Réponse courte'), ('essay', 'Question ouverte'), ('numerical', 'Réponse numérique'), ('matching', 'Appariement'), ('ordering', 'Classement')], max_length=20, verbose_name='Type de question')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Points')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage de la question", verbose_name='Ordre')),
                ('explanation', models.TextField(blank=True, help_text='Explication affichée après la réponse', verbose_name='Explication')),
                ('image', models.ImageField(blank=True, null=True, upload_to='quiz/questions/', verbose_name='Image')),
                ('correct_number', models.FloatField(blank=True, help_text='Réponse numérique correcte', null=True, verbose_name='Réponse numérique')),
                ('tolerance', models.FloatField(blank=True, default=0.1, help_text='Tolérance pour les réponses numériques', null=True, verbose_name='Tolérance')),
                ('correct_text', models.TextField(blank=True, help_text='Réponse texte correcte (une réponse par ligne)', verbose_name='Réponse texte')),
                ('case_sensitive', models.BooleanField(default=False, help_text='La casse est-elle importante pour la réponse ?', verbose_name='Sensible à la casse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['quiz', 'order', 'id'],
                'unique_together': {('quiz', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField(verbose_name='Texte du choix')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Réponse correcte')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage du choix", verbose_name='Ordre')),
                ('explanation', models.TextField(blank=True, help_text='Explication pour ce choix', verbose_name='Explication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
                'ordering': ['question', 'order', 'id'],
                'unique_together': {('question', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, help_text='Réponse textuelle pour questions ouvertes', verbose_name='Réponse texte')),
                ('numerical_answer', models.FloatField(blank=True, help_text='Réponse numérique', null=True, verbose_name='Réponse numérique')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Points obtenus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizattempt', verbose_name='Tentative')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='quiz.question', verbose_name='Question')),
                ('selected_choices', models.ManyToManyField(blank=True, help_text='Choix sélectionnés pour QCM/QCU/Vrai-Faux', to='quiz.choice', verbose_name='Choix sélectionnés')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
