# Generated by Django 5.0.6 on 2025-08-22 09:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0004_enrollment_trial_converted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de certificat"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        max_length=200, verbose_name="Nom du récipiendaire"
                    ),
                ),
                (
                    "course_title",
                    models.CharField(max_length=300, verbose_name="Titre du cours"),
                ),
                (
                    "completion_date",
                    models.DateTimeField(verbose_name="Date de completion"),
                ),
                (
                    "issue_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'émission",
                    ),
                ),
                (
                    "final_grade",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Note finale (%)",
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Pourcentage de completion",
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Durée totale (heures)",
                    ),
                ),
                (
                    "certificate_file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/generated/",
                        verbose_name="Fichier certificat",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certificates/pdf/",
                        verbose_name="Certificat PDF",
                    ),
                ),
                (
                    "verification_hash",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Hash de vérification"
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/qr_codes/",
                        verbose_name="Code QR de vérification",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("generated", "Généré"),
                            ("issued", "Délivré"),
                            ("revoked", "Révoqué"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Certificat visible publiquement",
                        verbose_name="Public",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données additionnelles du certificat",
                        verbose_name="Métadonnées",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_reason",
                    models.TextField(blank=True, verbose_name="Motif de révocation"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="courses.course",
                        verbose_name="Cours",
                    ),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="courses.enrollment",
                        verbose_name="Inscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificat",
                "verbose_name_plural": "Certificats",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificateShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_token",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="Token de partage"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expire le"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certificate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share",
                        to="certificates.certificate",
                        verbose_name="Certificat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partage de certificat",
                "verbose_name_plural": "Partages de certificats",
            },
        ),
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom du template"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("completion", "Completion de cours"),
                            ("achievement", "Réussite avec mention"),
                            ("participation", "Participation"),
                        ],
                        default="completion",
                        max_length=20,
                        verbose_name="Type de certificat",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image de fond (recommandé: 1920x1080px)",
                        null=True,
                        upload_to="certificates/templates/backgrounds/",
                        verbose_name="Image de fond",
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Couleur de fond hexadécimale (#RRGGBB)",
                        max_length=7,
                        verbose_name="Couleur de fond",
                    ),
                ),
                (
                    "border_color",
                    models.CharField(
                        default="#000000",
                        help_text="Couleur de la bordure hexadécimale",
                        max_length=7,
                        verbose_name="Couleur bordure",
                    ),
                ),
                (
                    "border_width",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[django.core.validators.MaxValueValidator(50)],
                        verbose_name="Épaisseur bordure (px)",
                    ),
                ),
                (
                    "title_text",
                    models.CharField(
                        default="CERTIFICAT DE COMPLETION",
                        max_length=200,
                        verbose_name="Titre principal",
                    ),
                ),
                (
                    "subtitle_text",
                    models.CharField(
                        blank=True,
                        default="est décerné à",
                        max_length=300,
                        verbose_name="Sous-titre",
                    ),
                ),
                (
                    "completion_text",
                    models.TextField(
                        default="pour avoir complété avec succès le cours",
                        verbose_name="Texte de completion",
                    ),
                ),
                (
                    "signature_text",
                    models.CharField(
                        default="Équipe pédagogique eSchool",
                        max_length=200,
                        verbose_name="Texte signature",
                    ),
                ),
                (
                    "title_font_size",
                    models.PositiveIntegerField(
                        default=48,
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="Taille police titre",
                    ),
                ),
                (
                    "name_font_size",
                    models.PositiveIntegerField(
                        default=36,
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="Taille police nom",
                    ),
                ),
                (
                    "course_font_size",
                    models.PositiveIntegerField(
                        default=28,
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="Taille police cours",
                    ),
                ),
                (
                    "title_color",
                    models.CharField(
                        default="#2c3e50", max_length=7, verbose_name="Couleur titre"
                    ),
                ),
                (
                    "name_color",
                    models.CharField(
                        default="#e74c3c", max_length=7, verbose_name="Couleur nom"
                    ),
                ),
                (
                    "course_color",
                    models.CharField(
                        default="#34495e", max_length=7, verbose_name="Couleur cours"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo de l'organisation (recommandé: 200x200px)",
                        null=True,
                        upload_to="certificates/templates/logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/templates/signatures/",
                        verbose_name="Image de signature",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Template par défaut"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de certificat",
                "verbose_name_plural": "Templates de certificats",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AddField(
            model_name="certificate",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="certificates.certificatetemplate",
                verbose_name="Template utilisé",
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["certificate_number"], name="certificate_certifi_cd0c46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["verification_hash"], name="certificate_verific_1316c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["user", "course"], name="certificate_user_id_2a7ce8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["status"], name="certificate_status_31e804_idx"),
        ),
    ]
