# Generated by Django 4.2.23 on 2025-08-18 16:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Classe Bootstrap Icons (ex: bi-book, bi-code-slash)', max_length=50, verbose_name='Icône')),
                ('color', models.CharField(default='#007bff', help_text='Couleur hexadécimale (#RRGGBB)', max_length=7, verbose_name='Couleur')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='courses.category', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.CharField(blank=True, help_text='Description courte pour les listes', max_length=300, verbose_name='Description courte')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='Image de couverture')),
                ('video_intro', models.URLField(blank=True, help_text="URL vers une vidéo d'introduction (YouTube, Vimeo, etc.)", verbose_name="Vidéo d'introduction")),
                ('difficulty', models.CharField(choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé'), ('expert', 'Expert')], default='beginner', max_length=20, verbose_name='Niveau de difficulté')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('es', 'Espagnol'), ('de', 'Allemand')], default='fr', max_length=2, verbose_name='Langue')),
                ('estimated_duration', models.DurationField(blank=True, help_text='Durée estimée totale du cours', null=True, verbose_name='Durée estimée')),
                ('max_students', models.PositiveIntegerField(blank=True, help_text="Nombre maximum d'étudiants (laisser vide pour illimité)", null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Nombre max d'étudiants")),
                ('is_free', models.BooleanField(default=True, verbose_name='Gratuit')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix')),
                ('currency', models.CharField(default='XAF', max_length=3, verbose_name='Devise')),
                ('prerequisites', models.TextField(blank=True, help_text='Connaissances requises avant de suivre ce cours', verbose_name='Prérequis')),
                ('learning_objectives', models.TextField(blank=True, help_text="Ce que l'étudiant apprendra dans ce cours", verbose_name="Objectifs d'apprentissage")),
                ('target_audience', models.TextField(blank=True, help_text="À qui s'adresse ce cours", verbose_name='Public cible')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé'), ('review', 'En révision')], default='draft', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Cours mis en avant')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('has_certificate', models.BooleanField(default=False, verbose_name='Délivre un certificat')),
                ('certificate_template', models.FileField(blank=True, null=True, upload_to='courses/certificates/', verbose_name='Modèle de certificat')),
                ('meta_description', models.CharField(blank=True, help_text='Description pour les moteurs de recherche', max_length=160, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=255, verbose_name='Meta mots-clés')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('enrollment_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'inscriptions")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='Catégorie')),
                ('co_instructors', models.ManyToManyField(blank=True, limit_choices_to={'role': 'instructor'}, related_name='co_created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Co-instructeurs')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Instructeur principal')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('lesson_type', models.CharField(choices=[('video', 'Vidéo'), ('text', 'Texte'), ('audio', 'Audio'), ('document', 'Document'), ('quiz', 'Quiz'), ('assignment', 'Devoir'), ('live', 'Session en direct'), ('external', 'Lien externe')], default='text', max_length=20, verbose_name='Type de leçon')),
                ('content', models.TextField(blank=True, verbose_name='Contenu textuel')),
                ('video_url', models.URLField(blank=True, help_text='URL YouTube, Vimeo ou autre', verbose_name='URL vidéo')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='courses/videos/', verbose_name='Fichier vidéo')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='courses/audio/', verbose_name='Fichier audio')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='courses/documents/', verbose_name='Document')),
                ('external_url', models.URLField(blank=True, help_text='Lien vers une ressource externe', verbose_name='URL externe')),
                ('duration', models.DurationField(blank=True, help_text='Durée de la leçon', null=True, verbose_name='Durée')),
                ('is_preview', models.BooleanField(default=False, help_text='Si coché, accessible avant inscription', verbose_name='Aperçu gratuit')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Cette leçon est-elle obligatoire pour la progression ?', verbose_name='Obligatoire')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publiée')),
                ('notes', models.TextField(blank=True, help_text="Notes pour l'instructeur", verbose_name='Notes privées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['module', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('color', models.CharField(default='#6c757d', help_text='Couleur hexadécimale', max_length=7, verbose_name='Couleur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mot-clé',
                'verbose_name_plural': 'Mots-clés',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_free', models.BooleanField(default=False, help_text='Si coché, ce module sera accessible gratuitement', verbose_name='Module gratuit')),
                ('estimated_duration', models.DurationField(blank=True, null=True, verbose_name='Durée estimée')),
                ('prerequisites', models.TextField(blank=True, help_text='Prérequis spécifiques à ce module', verbose_name='Prérequis')),
                ('learning_objectives', models.TextField(blank=True, help_text='Objectifs spécifiques de ce module', verbose_name='Objectifs')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['course', 'order', 'title'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document Word'), ('ppt', 'Présentation'), ('zip', 'Archive'), ('link', 'Lien'), ('image', 'Image'), ('other', 'Autre')], max_length=20, verbose_name='Type de ressource')),
                ('file', models.FileField(blank=True, null=True, upload_to='courses/resources/', verbose_name='Fichier')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('is_downloadable', models.BooleanField(default=True, verbose_name='Téléchargeable')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lesson', verbose_name='Leçon')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['lesson', 'order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='courses', to='courses.tag', verbose_name='Mots-clés'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'is_featured'], name='courses_cou_status_ee4b06_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'status'], name='courses_cou_categor_c23a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'status'], name='courses_cou_instruc_98570d_idx'),
        ),
    ]
