# Generated by Django 4.2.23 on 2025-08-20 08:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_enrollment_coursereview_coursefavorite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du bundle')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix du bundle')),
                ('individual_total_price', models.DecimalField(decimal_places=2, default=0, help_text='Calculé automatiquement', max_digits=10, verbose_name='Prix total individuel')),
                ('savings_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculé automatiquement', max_digits=10, verbose_name='Montant économisé')),
                ('savings_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Calculé automatiquement', max_digits=5, verbose_name="% d'économie")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valide à partir du')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('max_purchases', models.PositiveIntegerField(blank=True, null=True, verbose_name='Achats maximum')),
                ('current_purchases', models.PositiveIntegerField(default=0, verbose_name='Achats actuels')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='bundles/thumbnails/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(related_name='bundles', to='courses.course', verbose_name='Cours inclus')),
            ],
            options={
                'verbose_name': 'Bundle de cours',
                'verbose_name_plural': 'Bundles de cours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code devise')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('symbol', models.CharField(max_length=5, verbose_name='Symbole')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('exchange_rate_to_base', models.DecimalField(decimal_places=4, default=1.0, help_text='Taux de change vers la devise de base (XAF)', max_digits=10, verbose_name='Taux de change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('countries', models.JSONField(default=list, help_text="Codes pays ISO où ce niveau s'applique (ex: ['CM', 'SN', 'CI'])", verbose_name='Pays')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage de réduction')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Niveau de tarification',
                'verbose_name_plural': 'Niveaux de tarification',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code promo')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la promotion')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed_amount', 'Montant fixe'), ('free_trial_extended', 'Essai gratuit étendu'), ('free_access', 'Accès gratuit')], max_length=20, verbose_name='Type de réduction')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur de la réduction')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Montant maximum de réduction (pour les pourcentages)', max_digits=10, null=True, verbose_name='Réduction maximum')),
                ('minimum_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Montant minimum d'achat")),
                ('new_users_only', models.BooleanField(default=False, verbose_name='Nouveaux utilisateurs seulement')),
                ('usage_type', models.CharField(choices=[('single', 'Usage unique'), ('multiple', 'Usages multiples'), ('unlimited', 'Illimité')], default='multiple', max_length=20, verbose_name="Type d'usage")),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Utilisations maximum')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='Usage max par utilisateur')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Utilisations actuelles')),
                ('valid_from', models.DateTimeField(verbose_name='Valide à partir du')),
                ('valid_until', models.DateTimeField(verbose_name="Valide jusqu'au")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_combinable', models.BooleanField(default=False, verbose_name="Combinable avec d'autres codes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_bundles', models.ManyToManyField(blank=True, related_name='promotion_codes', to='courses.coursebundle', verbose_name='Bundles applicables')),
                ('applicable_courses', models.ManyToManyField(blank=True, related_name='promotion_codes', to='courses.course', verbose_name='Cours applicables')),
                ('eligible_users', models.ManyToManyField(blank=True, related_name='available_promotions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateurs éligibles')),
            ],
            options={
                'verbose_name': 'Code de promotion',
                'verbose_name_plural': 'Codes de promotion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix original')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant de la réduction')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix final')),
                ('currency', models.CharField(max_length=3, verbose_name='Devise')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Utilisé le')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence transaction')),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursebundle', verbose_name='Bundle')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Cours')),
                ('promotion_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='courses.promotioncode', verbose_name='Code promo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_usages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Utilisation de code promo',
                'verbose_name_plural': 'Utilisations de codes promo',
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('one_time', 'Paiement unique'), ('subscription', 'Abonnement'), ('per_module', 'Par module'), ('tiered', 'Prix échelonnés'), ('freemium', 'Freemium'), ('bundle', 'Bundle/Pack')], default='one_time', max_length=20, verbose_name='Type de tarification')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de base')),
                ('has_free_trial', models.BooleanField(default=False, verbose_name='Essai gratuit')),
                ('trial_duration_days', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Durée essai (jours)')),
                ('trial_access_type', models.CharField(blank=True, choices=[('preview', 'Aperçu seulement'), ('first_module', 'Premier module'), ('limited_time', 'Accès limité dans le temps'), ('full_access', 'Accès complet')], default='preview', max_length=20, verbose_name="Type d'accès en essai")),
                ('allow_individual_modules', models.BooleanField(default=False, verbose_name='Autoriser achat par module')),
                ('module_price_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Pourcentage du prix total par module', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% prix par module')),
                ('subscription_period', models.CharField(blank=True, choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], max_length=20, verbose_name="Période d'abonnement")),
                ('supports_installments', models.BooleanField(default=False, verbose_name='Paiement échelonné')),
                ('max_installments', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)], verbose_name="Maximum d'échéances")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.currency', verbose_name='Devise de base')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_model', to='courses.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Modèle de tarification',
                'verbose_name_plural': 'Modèles de tarification',
            },
        ),
        migrations.CreateModel(
            name='ModulePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix')),
                ('is_available_individually', models.BooleanField(default=True, verbose_name='Disponible individuellement')),
                ('requires_previous_modules', models.BooleanField(default=False, verbose_name='Nécessite les modules précédents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.currency', verbose_name='Devise')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_pricing', to='courses.module', verbose_name='Module')),
                ('prerequisite_modules', models.ManyToManyField(blank=True, related_name='unlocks_modules', to='courses.module', verbose_name='Modules prérequis')),
            ],
            options={
                'verbose_name': 'Tarification de module',
                'verbose_name_plural': 'Tarifications de modules',
            },
        ),
        migrations.AddField(
            model_name='coursebundle',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.currency', verbose_name='Devise'),
        ),
    ]
