# Generated by Django 4.2.23 on 2025-08-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursebundle_currency_pricingtier_promotioncode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='trial_converted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Conversion essai'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fin de l'essai"),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('trial', 'Essai gratuit'), ('completed', 'Terminé'), ('dropped', 'Abandonné'), ('expired', 'Expiré')], default='active', max_length=20, verbose_name='Statut'),
        ),
    ]
