# Generated by Django 4.2.23 on 2025-08-20 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True, verbose_name='Nom de la configuration')),
                ('api_key', models.CharField(help_text='Clé API Gemini', max_length=200)),
                ('model', models.CharField(choices=[('gemini-2.0-flash-exp', 'Gemini 2.0 Flash (Expérimental)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('gemini-1.5-flash', 'Gemini 1.5 Flash')], default='gemini-2.0-flash-exp', max_length=50, verbose_name='Modèle Gemini')),
                ('max_tokens', models.IntegerField(default=1000, help_text='Nombre maximum de tokens en réponse')),
                ('temperature', models.FloatField(default=0.7, help_text='Créativité des réponses (0.0 = déterministe, 1.0 = créatif)')),
                ('system_prompt', models.TextField(default="Tu es un assistant virtuel intelligent pour une plateforme d'e-learning. Tu aides les utilisateurs avec leurs questions sur les cours, les paiements, et l'utilisation de la plateforme. Réponds toujours de manière utile, précise et amicale en français.", verbose_name='Prompt système')),
                ('enable_knowledge_base', models.BooleanField(default=True, help_text='Utiliser la base de connaissances pour enrichir les réponses')),
                ('enable_context_memory', models.BooleanField(default=True, help_text='Garder en mémoire le contexte des conversations')),
                ('max_context_messages', models.IntegerField(default=10, help_text='Nombre maximum de messages précédents à inclure dans le contexte')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Assistant',
                'verbose_name_plural': 'Configurations Assistant',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='ID de session pour les utilisateurs anonymes', max_length=100)),
                ('title', models.CharField(blank=True, help_text='Titre généré automatiquement basé sur le premier message', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('context_data', models.JSONField(default=dict, help_text='Données de contexte (cours actuel, préférences utilisateur, etc.)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5)),
                ('response_style', models.CharField(choices=[('formal', 'Formel'), ('casual', 'Décontracté'), ('technical', 'Technique')], default='casual', max_length=20)),
                ('enable_suggestions', models.BooleanField(default=True, help_text="Recevoir des suggestions proactives de l'assistant")),
                ('enable_course_recommendations', models.BooleanField(default=True, help_text='Recevoir des recommandations de cours')),
                ('save_conversation_history', models.BooleanField(default=True, help_text="Sauvegarder l'historique des conversations")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférences utilisateur',
                'verbose_name_plural': 'Préférences utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant'), ('system', 'Système')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict, help_text='Métadonnées comme les tokens utilisés, temps de réponse, etc.')),
                ('is_helpful', models.BooleanField(blank=True, help_text="L'utilisateur a-t-il trouvé cette réponse utile?", null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('category', models.CharField(choices=[('general', 'Général'), ('courses', 'Cours'), ('payments', 'Paiements'), ('account', 'Compte utilisateur'), ('technical', 'Support technique'), ('enrollment', 'Inscription'), ('certificates', 'Certificats')], default='general', max_length=20, verbose_name='Catégorie')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('keywords', models.TextField(blank=True, help_text='Mots-clés séparés par des virgules pour améliorer la recherche')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('priority', models.IntegerField(default=0, help_text="Priorité d'affichage (plus élevé = plus prioritaire)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Nombre de fois que cette entrée a été utilisée')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrée de base de connaissances',
                'verbose_name_plural': 'Base de connaissances',
                'ordering': ['-priority', '-updated_at'],
            },
        ),
    ]
