# Generated by Django 5.0.6 on 2025-08-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistantconfiguration",
            name="api_key",
            field=models.CharField(
                help_text="AIzaSyC3cdxJrrEZ15dhj6TeU9hbEh2stAXeI2E", max_length=200
            ),
        ),
    ]
