# Generated by Django 5.0.6 on 2025-08-21 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0004_enrollment_trial_converted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("live", "Cours en direct"),
                            ("deadline", "Échéance"),
                            ("exam", "Examen"),
                            ("assignment", "Devoir"),
                        ],
                        default="live",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Planifié"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                            ("cancelled", "Annulé"),
                            ("postponed", "Reporté"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(help_text="Date et heure prévues"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, help_text="Durée en minutes"
                    ),
                ),
                (
                    "access_link",
                    models.URLField(
                        blank=True, help_text="Lien d'accès au cours en direct"
                    ),
                ),
                (
                    "meeting_id",
                    models.CharField(
                        blank=True, help_text="ID de réunion", max_length=100
                    ),
                ),
                (
                    "access_code",
                    models.CharField(
                        blank=True, help_text="Code d'accès", max_length=50
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre maximum de participants",
                        null=True,
                    ),
                ),
                ("auto_reminder", models.BooleanField(default=True)),
                (
                    "reminder_hours_before",
                    models.PositiveIntegerField(
                        default=24, help_text="Heures avant pour l'envoi du rappel"
                    ),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notes pour l'instructeur"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="courses.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planning de cours",
                "verbose_name_plural": "Plannings de cours",
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Titre de l'événement", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description détaillée"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("course", "Cours"),
                            ("quiz", "Quiz"),
                            ("deadline", "Échéance"),
                            ("meeting", "Réunion"),
                            ("reminder", "Rappel"),
                            ("holiday", "Congé"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="reminder",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyenne"),
                            ("high", "Élevée"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Date et heure de début"),
                ),
                ("end_date", models.DateTimeField(help_text="Date et heure de fin")),
                (
                    "all_day",
                    models.BooleanField(
                        default=False, help_text="Événement toute la journée"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Lieu de l'événement", max_length=200
                    ),
                ),
                (
                    "online_link",
                    models.URLField(
                        blank=True, help_text="Lien pour événement en ligne"
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, help_text="Événement récurrent"),
                ),
                (
                    "recurrence_rule",
                    models.TextField(
                        blank=True,
                        help_text="Règle de récurrence (format RRULE RFC 5545)",
                    ),
                ),
                (
                    "reminder_enabled",
                    models.BooleanField(default=True, help_text="Activer les rappels"),
                ),
                (
                    "reminder_minutes_before",
                    models.PositiveIntegerField(
                        default=15, help_text="Minutes avant l'événement pour le rappel"
                    ),
                ),
                (
                    "email_reminder",
                    models.BooleanField(default=False, help_text="Rappel par email"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3498db",
                        help_text="Couleur d'affichage (format hex)",
                        max_length=7,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Visible publiquement"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Événement actif"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        help_text="Organisateur de l'événement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Événement parent si c'est une occurrence récurrente",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_instances",
                        to="scheduler.event",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Participants à l'événement",
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="EventReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("push", "Notification push"),
                            ("sms", "SMS"),
                            ("in_app", "Notification in-app"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("sent", "Envoyé"),
                            ("delivered", "Délivré"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("scheduled_send_time", models.DateTimeField()),
                ("actual_send_time", models.DateTimeField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="scheduler.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rappel d'événement",
                "verbose_name_plural": "Rappels d'événements",
                "ordering": ["scheduled_send_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registered",
                    models.BooleanField(default=True, help_text="Inscrit à la session"),
                ),
                (
                    "attended",
                    models.BooleanField(default=False, help_text="A participé"),
                ),
                ("join_time", models.DateTimeField(blank=True, null=True)),
                ("leave_time", models.DateTimeField(blank=True, null=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Note sur 5", null=True
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, help_text="Commentaire de l'étudiant"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="scheduler.courseschedule",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence",
                "verbose_name_plural": "Présences",
            },
        ),
        migrations.AddField(
            model_name="courseschedule",
            name="enrolled_students",
            field=models.ManyToManyField(
                related_name="course_schedules",
                through="scheduler.ScheduleAttendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["start_date", "end_date"], name="scheduler_e_start_d_7b79f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organizer", "start_date"],
                name="scheduler_e_organiz_56c45f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type", "is_active"],
                name="scheduler_e_event_t_969dd3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventreminder",
            unique_together={("event", "user", "reminder_type")},
        ),
        migrations.AlterUniqueTogether(
            name="scheduleattendance",
            unique_together={("schedule", "student")},
        ),
        migrations.AddIndex(
            model_name="courseschedule",
            index=models.Index(
                fields=["course", "scheduled_date"],
                name="scheduler_c_course__2f770a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="courseschedule",
            index=models.Index(
                fields=["schedule_type", "status"],
                name="scheduler_c_schedul_d38e63_idx",
            ),
        ),
    ]
